version: '3.8'

services:

  db:
    image: postgres:15-alpine
    container_name: case-itau-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=testdb
    volumes:
      - "./schema.sql:/docker-entrypoint-initdb.d/init.sql"

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: case-itau-backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - DB_DATABASE=testdb
    depends_on:
      - db